### ISSUE TITLE
Localise existing views

### ISSUE THREAD

**Issue by DavidBiddle** [alphagov/forms-admin#60]
We recently added localisation to the repo (https://github.com/alphagov/forms-admin/pull/56) and from this point on we will be localising any new views or components we create. However, there are existing views which still have hard-coded English text in them. 

We should complete this issue before we start adding support for other languages.

This affects:
`forms/`
- [x] `edit.html.erb`
- [x] `new.html.erb`
- [x] `not_found.html.erb`
- [x] `show.html.erb`

`home/`
- [x] `index.html.erb`

`layouts/`
- [x] `application.html.erb`

**Comment by 0atman** [comment]
Add Spec tests for localisation? (like in the runner)
